version: 2.1
orbs:
  macos: circleci/macos@1.0.0
  xcode: circleci/xcode@3.2.0
jobs:
  build:
    macos:
      xcode: 15.3.0
    steps:
      - checkout
      - xcode/test:
          workspace: MyApp.xcworkspace
          scheme: MyApp
workflows:
  version: 2.1
  build:
    jobs:
      - build