# .circleci/config.yml
version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - beta_release
jobs:
  beta_release:
    macos:
      xcode: "15.3.0"  # Specify the Xcode version, match with your project requirements
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # Install specific version of Fastlane, or use bundler if Gemfile is used
            gem install fastlane -NV
      - run:
          name: Execute Fastlane Beta Lane
          command: fastlane beta
