# .circleci/config.yml
version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - beta_release
jobs:
  beta_release:
    macos:
      xcode: "15.3.0"  # Specify the Xcode version, match with your project requirements
    steps:
      - checkout
      - run:
          name: Install rbenv and Ruby
          command: |
            brew install rbenv
            echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> $BASH_ENV
            source $BASH_ENV
            rbenv install -s 3.2.0
            rbenv global 3.2.0
      - run:
          name: Install Bundler and dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle
      - run:
          name: Install Bundler
          command: bundle config set path 'vendor/bundle'
      - run:
          name: Execute Fastlane Beta Lane
          command: bundle exec fastlane beta
