# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Just build, no signing or upload"
  lane :justbuild do
    xcversion(version: "15.3")
    match(type: "development")
    increment_build_number(xcodeproj: "SpellingAppOnline.xcodeproj")
    build_app(scheme: "SpellingAppOnline",
      configuration: "Debug",
      export_method: "development",
      export_xcargs: "-allowProvisioningUpdates")
  end

  desc "Build for App Store distribution and upload to TestFlight"
  lane :beta do
    xcversion(version: "15.3")  # Ensure you have this version installed
    match(type: "appstore")  # Fetch distribution certificates and profiles
    increment_build_number(xcodeproj: "SpellingAppOnline.xcodeproj")
    build_app(scheme: "SpellingAppOnline", 
              workspace: "SpellingAppOnline.xcworkspace",
              configuration: "Release",
              export_method: "app-store",  # Updated export method
              export_xcargs: "-allowProvisioningUpdates")
    app_store_connect_api_key(
              key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
              issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
              key_content: ENV['APP_STORE_CONNECT_API_KEY_FILE_BASE64'],
              is_key_content_base64: true,
              in_house: ENV['APP_STORE_CONNECT_API_KEY_IN_HOUSE'] == "true")
    upload_to_testflight
  end
  

end
