# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "SpellingAppOnline.xcodeproj")
    build_app(scheme: "SpellingAppOnline")
    app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_API_KEY_FILE_BASE64'],
    is_key_content_base64: true,
    in_house: ENV['APP_STORE_CONNECT_API_KEY_IN_HOUSE'] == "true"
  )
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight"
  lane :justbuild do
    increment_build_number(xcodeproj: "SpellingAppOnline.xcodeproj")
    xcversion(version: "15.3")
    build_app(scheme: "SpellingAppOnline")
  end

end
