name: iOS Development Build

on:
  push:
    branches:
      - githubactions  # Triggers when you push to the main branch
  pull_request:
    branches:
      - main  # Also triggers on pull requests to the main branch

jobs:
  build:
    runs-on: macos-latest
    environment: buildWithgithubaction

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'

        # Cache Ruby gems
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Fastlane build
        run: bundle exec fastlane build_adhoc_app
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPFILE_APP_IDENTIFIER: ${{ secrets.APPFILE_APP_IDENTIFIER }}
          APPFILE_APPLE_ID: ${{ secrets.APPFILE_APPLE_ID }}
          APPFILE_TEAM_ID: ${{ secrets.APPFILE_TEAM_ID }}
          APPFILE_ITC_TEAM_ID: ${{ secrets.APPFILE_ITC_TEAM_ID }}
          APPFILE_APPLE_PASSWORD: ${{ secrets.APPFILE_APPLE_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_FILEPATH: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_FILEPATH }}
          APP_STORE_CONNECT_API_KEY_FILE_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE_BASE64 }}