name: Submit to App Store

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: macos-15
    environment: buildWithgithubaction

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'

        # Cache Ruby gems
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: submit to store
        run: bundle exec fastlane releaseLatestTestFlightBuildToAppStoreGitHubAction
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPFILE_APP_IDENTIFIER: ${{ secrets.APPFILE_APP_IDENTIFIER }}
          APPFILE_APPLE_ID: ${{ secrets.APPFILE_APPLE_ID }}
          APPFILE_TEAM_ID: ${{ secrets.APPFILE_TEAM_ID }}
          APPFILE_ITC_TEAM_ID: ${{ secrets.APPFILE_ITC_TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_FILE_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE_BASE64 }}
          APP_STORE_CONNECT_API_KEY_IN_HOUSE: ${{ secrets.APP_STORE_CONNECT_API_KEY_IN_HOUSE }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  